- hosts: "{{ hosts }}"
  name: Run the remaining tests on all hosts
  gather_facts: yes
  serial: "100%"

  vars:
    pathToScripts: "{{ pathToScript }}"
    pathToStorage: "{{ pathToStorage }}"
    testType: "{{ testType }}"
    pathToResults: "{{pathToResults }}"
    clientSet:
    testNum: "{{ testNum }}"
    slashvar: "/"
    systemStorage: "{{ systemStorage }}"
    clientSet: "{{ clientSet }}"
    pathToLocalResults: "{{ pathToLocalResults }}"

  tasks:
    
    - name: Full Path
      shell: echo "{{ pathToResults }}{{ clientSet }}/{{ testNum }}"
      register: fullPathToResults
    
    - name: check that clientSet directory exists
      stat:
        path: "{{ pathToResults }}{{ clientSet }}"
      register: clientSetExists

    - name: make ClientSet Dir
      shell: mkdir "{{ pathToResults }}{{ clientSet }}"
      when: clientSetExists.stat.exists

    - name: check for testNum
      stat:
        path: "{{ fullPathToResults.stdout }}"
      register: testNumExists

    - name: Make testNum dir
      shell: mkdir "{{ fullPathToResults }}"
      when: testNumExists.stat.exists

    - name: get LocalHost IP
      shell: ip=`hostname -I`; octet=${ip:0:13}; echo "${octet}:"
      register: localhost
      delegate_to: localhost

    - name: get full vastpath 
      shell: ls / | grep vast1 > /tmp/temp.txt && sed -n 1p /tmp/temp.txt > /tmp/holder.txt; printf "/" && printf `cat /tmp/holder.txt` && printf "/frametest/" && printf `hostname` && printf "/"
      register: fullPath
      when:  systemStorage == "vast"

    - name: get full gpfs path
      shell: echo "{{ pathToStorage }}"
      register: fullPath
      when: systemStorage == "gpfs"

    - name: IP Variable
      shell: echo `ip route get 1.2.3.4 | awk '{print $7}'`
      register: ipAddress

    - name: send optimal frametest
      copy:
        src: "{{ pathToScripts }}"
        dest: /etc/ansible/scripts    

    - name: ensure everything is the proper permissions
      shell: chmod 755 /etc/ansible/scripts/*
    
    - name: Path to Script
      shell: echo "/etc/ansible/scripts/"`ls /etc/ansible/scripts/ | grep "frametest_""{{ipAddress.stdout }}""_optimal.sh"`
      register: pathToFrametest
      when: testType == "frametest"

    - name: Path to Script
      shell: echo "/etc/ansible/scripts/"`ls /etc/ansible/scripts/ | grep "fio_""{{ ipAddress.stdout }}""_optimal.sh"`
      register: pathToFio
      when: testType == "fio"
    
    - name: Execute Frametest.sh Vast
      shell: "{{ pathToFrametest.stdout }} {{ fullVastPath.stdout }} {{ fullPathToResults.stdout }} {{ pathToScripts }}"
      when: testType == "frametest" and systemStorage == "vast"

    - name: Execute fio Vast
      shell: "{{ pathToFio.stdout }} {{ fullVastPath.stdout }} {{ fullPathToResults.stdout }}/ {{ pathToScripts }}"
      when: testType == "fio" and systemStorage == "vast"

    - name: Execute Frametest.sh
      shell: "{{ pathToFrametest.stdout }} {{ fullGPFSPath.stdout }} {{ fullPathToResults.stdout }} {{ pathToScripts }}"
      when: testType == "frametest" and systemStorage == "gpfs"

    - name: Execute fio
      shell: "{{ pathToFio.stdout }} {{ fullGPFSPath.stdout }} {{ fullPathToResults.stdout }}/ {{ pathToScripts }}"
      when: testType == "fio" and systemStorage == "gpfs"
    
    - name: Fetch Results Files
      shell: rsync -av "{{ fullPathToResults.stdout }}"  "{{ localhost.stdout }}{{ pathToLocalResults }}"
    
