- hosts: "{{ hosts }}"
  name: LOAD TEST
  gather_facts: yes
  serial: 1
  strategy: linear

  vars:
    pathToScripts: "{{ pathToScript }}"
    pathToStorage: "{{ pathToStorage }}"
    testType: "{{ testType }}"
    pathToResult:  "{{ pathToResults }}"
    slashVar: "/"
    systemStorage: "{{ systemStorage }}"
    w: "{{ w }}"
    t: "{{ t }}"
    bs: "{{ bs }}"
    iod: "{{ iod }}"
    nj: "{{ nj }}"

  tasks:

    - name: Get Localhost IP
      shell: ip=`hostname -I`; octet=${ip:0:13}; echo "${octet}:"
      register: localhost
      delegate_to: localhost

    - name: Get Hostname
      shell: echo `hostname`
      register: hostname

    
    - name: get full vastpath 
      shell: ls / | grep vast1 > /tmp/temp.txt && sed -n 1p /tmp/temp.txt > /tmp/holder.txt; printf "/" && printf `cat /tmp/holder.txt` && printf "/frametest/" && printf `hostname` && printf "/"
      register: fullVastPath
      when: systemStorage == "vast"

    - name: get full gpfs path
      shell: echo "{{ pathToStorage }}{{ hostname.stdout }}/"
      register: fullGPFSPath
      when: systemStorage == "gpfs"

    - debug:
        var: w

    - name: ensure everything is the proper permissions
      shell: chmod 755 /etc/ansible/scripts/*
    
    - name: IP Variable
      shell: ip route get 1.2.3.4 | awk '{print $7}'
      register: ipAddress

    - name: Execute Frametest.sh vast
      shell: /etc/ansible/scripts/frametest.sh "{{ fullVastPath.stdout }}" "{{ pathToResults }}" "{{ pathToScripts }}" "{{ w }}" "{{ t }}"
      when: testType == "frametest" and systemStorage == "vast"

    - name: Execute Frametest.sh gpfs
      shell: /etc/ansible/scripts/frametest.sh "{{ fullGPFSPath.stdout }}" "{{ pathToResults }}" "{{ pathToScripts }}" "{{ w }}" "{{ t }}"
      when: testType == "frametest" and systemStorage == "gpfs"

    - name: Execute fio vast
      shell: /etc/ansible/scripts/fio.sh "{{ fullVastPath.stdout }}" "{{ pathToResults }}" "{{ pathToScripts }}" "{{ bs }}" "{{ iod }}" "{{ nj }}"
      when: testType == "fio" and systemStorage == "vast"

    - name: Execute fio gpfs
      shell: /etc/ansible/scripts/fio.sh "{{ fullGPFSPath.stdout }}" "{{ pathToResults }}" "{{ pathToScripts }}" "{{ bs }}" "{{ iod }}" "{{ nj }}"
      when: testType == "fio" and systemStorage == "gpfs"
 
    - name: Fetch Results Files
      shell: rsync -av "{{ pathToResults }}" "{{ localhost.stdout }}{{ pathToResults }}Client_1/{{ ipAddress.stdout }}/"
    
       
